### ISSUE TITLE
Please support IPv4

### ISSUE THREAD

**Issue by joshtriplett** [cperciva/ec2-boot-bench#4]
I'd like to test ec2-boot-bench from a network that doesn't have IPv6 support. Would you be amenable to a patch adding IPv4 support?

**Comment by cperciva** [comment]
It already has IPv4 support; what it doesn't have is lack-of-IPv6 support.  But yes, happy to have such a change; add a new `--no-ipv6` option and make the `Ipv6AddressCount=1` bit in `launch` conditional on that.

**Comment by joshtriplett** [comment]
Ah, I was thrown off when reading the code by the use of `[%s]:22` to construct an address. As far as I can tell, the square-bracket address form like that isn't normally legal for IPv4, only IPv6, but it looks like `sock_resolve` accepts it.

I'll submit a patch for `--no-ipv6` then.

**Comment by joshtriplett** [comment]
Done in https://github.com/cperciva/ec2-boot-bench/pull/5 , along with an option to specify a security group.

**Comment by joshtriplett** [comment]
Fixed in https://github.com/cperciva/ec2-boot-bench/commit/a84713408db262608700f950a259cedc3f2e3fe1 via #5.
